<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Modules\AcademicPeriods\Application\UGTM.Modules.AcademicPeriods.Application.csproj" />
    <ProjectReference Include="..\..\Modules\AcademicPeriods\Contracts\UGTM.Modules.AcademicPeriods.Contracts.csproj" />
    <ProjectReference Include="..\..\Modules\AcademicPeriods\Domain\UGTM.Modules.AcademicPeriods.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\AcademicPeriods\Infrastructure\UGTM.Modules.AcademicPeriods.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\DefenseCouncil\Application\UGTM.Modules.DefenseCouncil.Application.csproj" />
    <ProjectReference Include="..\..\Modules\DefenseCouncil\Contracts\UGTM.Modules.DefenseCouncil.Contracts.csproj" />
    <ProjectReference Include="..\..\Modules\DefenseCouncil\Domain\UGTM.Modules.DefenseCouncil.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\DefenseCouncil\Infrastructure\UGTM.Modules.DefenseCouncil.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\FinalReportEvaluation\Application\UGTM.Modules.FinalReportEvaluation.Application.csproj" />
    <ProjectReference Include="..\..\Modules\FinalReportEvaluation\Contracts\UGTM.Modules.FinalReportEvaluation.Contracts.csproj" />
    <ProjectReference Include="..\..\Modules\FinalReportEvaluation\Domain\UGTM.Modules.FinalReportEvaluation.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\FinalReportEvaluation\Infrastructure\UGTM.Modules.FinalReportEvaluation.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\GradingConsolidation\Application\UGTM.Modules.GradingConsolidation.Application.csproj" />
    <ProjectReference Include="..\..\Modules\GradingConsolidation\Contracts\UGTM.Modules.GradingConsolidation.Contracts.csproj" />
    <ProjectReference Include="..\..\Modules\GradingConsolidation\Domain\UGTM.Modules.GradingConsolidation.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\GradingConsolidation\Infrastructure\UGTM.Modules.GradingConsolidation.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Identity\Application\UGTM.Modules.Identity.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Identity\Contracts\UGTM.Modules.Identity.Contracts.csproj" />
    <ProjectReference Include="..\..\Modules\Identity\Domain\UGTM.Modules.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\Identity\Infrastructure\UGTM.Modules.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\MidtermProgress\Application\UGTM.Modules.MidtermProgress.Application.csproj" />
    <ProjectReference Include="..\..\Modules\MidtermProgress\Contracts\UGTM.Modules.MidtermProgress.Contracts.csproj" />
    <ProjectReference Include="..\..\Modules\MidtermProgress\Domain\UGTM.Modules.MidtermProgress.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\MidtermProgress\Infrastructure\UGTM.Modules.MidtermProgress.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Notifications\Application\UGTM.Modules.Notifications.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Notifications\Contracts\UGTM.Modules.Notifications.Contracts.csproj" />
    <ProjectReference Include="..\..\Modules\Notifications\Domain\UGTM.Modules.Notifications.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\Notifications\Infrastructure\UGTM.Modules.Notifications.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\ThesisManagement\Application\UGTM.Modules.ThesisManagement.Application.csproj" />
    <ProjectReference Include="..\..\Modules\ThesisManagement\Contracts\UGTM.Modules.ThesisManagement.Contracts.csproj" />
    <ProjectReference Include="..\..\Modules\ThesisManagement\Domain\UGTM.Modules.ThesisManagement.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\ThesisManagement\Infrastructure\UGTM.Modules.ThesisManagement.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\TopicCatalog\Application\UGTM.Modules.TopicCatalog.Application.csproj" />
    <ProjectReference Include="..\..\Modules\TopicCatalog\Contracts\UGTM.Modules.TopicCatalog.Contracts.csproj" />
    <ProjectReference Include="..\..\Modules\TopicCatalog\Domain\UGTM.Modules.TopicCatalog.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\TopicCatalog\Infrastructure\UGTM.Modules.TopicCatalog.Infrastructure.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Application\UGTM.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Domain\UGTM.BuildingBlocks.Domain.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Infrastructure\UGTM.BuildingBlocks.Infrastructure.csproj" />
  </ItemGroup>

</Project>