<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Application\UGTM.Modules.TopicCatalog.Application.csproj" />
    <ProjectReference Include="..\Domain\UGTM.Modules.TopicCatalog.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Infrastructure\UGTM.BuildingBlocks.Infrastructure.csproj" />
  </ItemGroup>

</Project>
